
export let role = "admin";


export const calendarEvents = [
    // Monday (March 31st)
    { title: "Biology", allDay: false, start: new Date(2025, 2, 31, 8, 0), end: new Date(2025, 2, 31, 8, 45) },
    { title: "English Literature", allDay: false, start: new Date(2025, 2, 31, 9, 0), end: new Date(2025, 2, 31, 9, 45) },
    { title: "Mathematics", allDay: false, start: new Date(2025, 2, 31, 10, 0), end: new Date(2025, 2, 31, 10, 45) },
    { title: "Physics", allDay: false, start: new Date(2025, 2, 31, 11, 0), end: new Date(2025, 2, 31, 11, 45) },
    { title: "Lunch Break", allDay: false, start: new Date(2025, 2, 31, 12, 0), end: new Date(2025, 2, 31, 12, 45) },
    { title: "History", allDay: false, start: new Date(2025, 2, 31, 13, 0), end: new Date(2025, 2, 31, 13, 45) },
    { title: "Chemistry Lab", allDay: false, start: new Date(2025, 2, 31, 14, 0), end: new Date(2025, 2, 31, 14, 45) },
    { title: "Computer Science", allDay: false, start: new Date(2025, 2, 31, 15, 0), end: new Date(2025, 2, 31, 15, 45) },

    // Continue for Tuesday (April 1st) - Saturday (April 5th)
    ...Array.from({ length: 5 }, (_, i) => {
        const day = i + 1;
        return [
            { title: "Geography", allDay: false, start: new Date(2025, 3, day, 8, 0), end: new Date(2025, 3, day, 8, 45) },
            { title: "Mathematics", allDay: false, start: new Date(2025, 3, day, 9, 0), end: new Date(2025, 3, day, 9, 45) },
            { title: "Physics", allDay: false, start: new Date(2025, 3, day, 10, 0), end: new Date(2025, 3, day, 10, 45) },
            { title: "English", allDay: false, start: new Date(2025, 3, day, 11, 0), end: new Date(2025, 3, day, 11, 45) },
            { title: "Lunch Break", allDay: false, start: new Date(2025, 3, day, 12, 0), end: new Date(2025, 3, day, 12, 45) },
            { title: "History", allDay: false, start: new Date(2025, 3, day, 13, 0), end: new Date(2025, 3, day, 13, 45) },
            { title: "Chemistry", allDay: false, start: new Date(2025, 3, day, 14, 0), end: new Date(2025, 3, day, 14, 45) },
            { title: "Computer Science", allDay: false, start: new Date(2025, 3, day, 15, 0), end: new Date(2025, 3, day, 15, 45) }
        ];
    }).flat()
];

export const TeachercalendarEvents = [
    // Teacher: Ms. Nakato (Biology) - Assuming she teaches multiple classes
    // Monday
    { title: "Biology - Class A", allDay: false, start: new Date(2025, 3, 7, 8, 0), end: new Date(2025, 3, 7, 8, 45), resourceId: "nakato" },
    { title: "Biology - Class B", allDay: false, start: new Date(2025, 3, 7, 9, 0), end: new Date(2025, 3, 7, 9, 45), resourceId: "nakato" },
    { title: "Biology - Class C", allDay: false, start: new Date(2025, 3, 7, 11, 0), end: new Date(2025, 3, 7, 11, 45), resourceId: "nakato" },
    // Tuesday
    { title: "Biology - Class B", allDay: false, start: new Date(2025, 3, 8, 8, 0), end: new Date(2025, 3, 8, 8, 45), resourceId: "nakato" },
    { title: "Biology - Class A", allDay: false, start: new Date(2025, 3, 8, 10, 0), end: new Date(2025, 3, 8, 10, 45), resourceId: "nakato" },
    { title: "Biology - Class C", allDay: false, start: new Date(2025, 3, 8, 12, 0), end: new Date(2025, 3, 8, 12, 45), resourceId: "nakato" },
    // Wednesday
    { title: "Biology - Class A", allDay: false, start: new Date(2025, 3, 9, 8, 0), end: new Date(2025, 3, 9, 8, 45), resourceId: "nakato" },
    { title: "Biology - Class B", allDay: false, start: new Date(2025, 3, 9, 9, 0), end: new Date(2025, 3, 9, 9, 45), resourceId: "nakato" },
    { title: "Biology - Class C", allDay: false, start: new Date(2025, 3, 9, 11, 0), end: new Date(2025, 3, 9, 11, 45), resourceId: "nakato" },

    // Teacher: Mr. Okello (Mathematics)
    // Monday
    { title: "Mathematics - Class C", allDay: false, start: new Date(2025, 3, 7, 9, 0), end: new Date(2025, 3, 7, 9, 45), resourceId: "okello" },
    { title: "Mathematics - Class A", allDay: false, start: new Date(2025, 3, 7, 10, 0), end: new Date(2025, 3, 7, 10, 45), resourceId: "okello" },
    { title: "Mathematics - Class B", allDay: false, start: new Date(2025, 3, 7, 12, 0), end: new Date(2025, 3, 7, 12, 45), resourceId: "okello" },
    // Tuesday
    { title: "Mathematics - Class A", allDay: false, start: new Date(2025, 3, 8, 9, 0), end: new Date(2025, 3, 8, 9, 45), resourceId: "okello" },
    { title: "Mathematics - Class B", allDay: false, start: new Date(2025, 3, 8, 11, 0), end: new Date(2025, 3, 8, 11, 45), resourceId: "okello" },
    { title: "Mathematics - Class C", allDay: false, start: new Date(2025, 3, 8, 13, 0), end: new Date(2025, 3, 8, 13, 45), resourceId: "okello" },
    // Wednesday
    { title: "Mathematics - Class C", allDay: false, start: new Date(2025, 3, 9, 9, 0), end: new Date(2025, 3, 9, 9, 45), resourceId: "okello" },
    { title: "Mathematics - Class A", allDay: false, start: new Date(2025, 3, 9, 10, 0), end: new Date(2025, 3, 9, 10, 45), resourceId: "okello" },
    { title: "Mathematics - Class B", allDay: false, start: new Date(2025, 3, 9, 12, 0), end: new Date(2025, 3, 9, 12, 45), resourceId: "okello" },

    // Teacher: Ms. Adongo (English)
    // Monday
    { title: "English - Class B", allDay: false, start: new Date(2025, 3, 7, 10, 0), end: new Date(2025, 3, 7, 10, 45), resourceId: "adongo" },
    { title: "English - Class C", allDay: false, start: new Date(2025, 3, 7, 12, 0), end: new Date(2025, 3, 7, 12, 45), resourceId: "adongo" },
    // Tuesday
    { title: "English - Class C", allDay: false, start: new Date(2025, 3, 8, 9, 0), end: new Date(2025, 3, 8, 9, 45), resourceId: "adongo" },
    { title: "English - Class A", allDay: false, start: new Date(2025, 3, 8, 11, 0), end: new Date(2025, 3, 8, 11, 45), resourceId: "adongo" },
    // Wednesday
    { title: "English - Class B", allDay: false, start: new Date(2025, 3, 9, 10, 0), end: new Date(2025, 3, 9, 10, 45), resourceId: "adongo" },
    { title: "English - Class A", allDay: false, start: new Date(2025, 3, 9, 13, 0), end: new Date(2025, 3, 9, 13, 45), resourceId: "adongo" },
];
export const teachersData = [
    {
        id: 1,
        teacherId: "TCH001",
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "123-456-7890",
        subjects: ["Mathematics", "Physics"],
        classes: ["10A", "11B"],
        address: "123 Main St, Anytown",
    },
    {
        id: 2,
        teacherId: "TCH002",
        name: "Bob Smith",
        email: "bob.smith@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "987-654-3210",
        subjects: ["English", "History"],
        classes: ["9C", "12A"],
        address: "456 Oak Ave, Anytown",
    },
    {
        id: 3,
        teacherId: "TCH003",
        name: "Carol Williams",
        email: "carol.williams@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "555-123-4567",
        subjects: ["Biology", "Chemistry"],
        classes: ["11A", "10B"],
        address: "789 Pine Ln, Anytown",
    },
    {
        id: 4,
        teacherId: "TCH004",
        name: "David Brown",
        email: "david.brown@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "111-222-3333",
        subjects: ["Computer Science", "Geography"],
        classes: ["12B", "9A"],
        address: "101 Elm Rd, Anytown",
    },
    {
        id: 5,
        teacherId: "TCH005",
        name: "Eve Davis",
        email: "eve.davis@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "444-555-6666",
        subjects: ["Art", "Music"],
        classes: ["10C", "11C"],
        address: "202 Maple Dr, Anytown",
    },
    {
        id: 6,
        teacherId: "TCH006",
        name: "Frank Miller",
        email: "frank.miller@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "777-888-9999",
        subjects: ["Physical Education", "Drama"],
        classes: ["9B", "12C"],
        address: "303 Cedar Ct, Anytown",
    },
    {
        id: 7,
        teacherId: "TCH007",
        name: "Grace Wilson",
        email: "grace.wilson@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "222-333-4444",
        subjects: ["Mathematics", "History"],
        classes: ["11B", "10A"],
        address: "404 Birch Pl, Anytown",
    },
    {
        id: 8,
        teacherId: "TCH008",
        name: "Henry Moore",
        email: "henry.moore@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "666-777-8888",
        subjects: ["English", "Chemistry"],
        classes: ["12A", "9C"],
        address: "505 Willow Way, Anytown",
    },
    {
        id: 9,
        teacherId: "TCH009",
        name: "Ivy Taylor",
        email: "ivy.taylor@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "333-444-5555",
        subjects: ["Physics", "Biology"],
        classes: ["10B", "11A"],
        address: "606 Spruce St, Anytown",
    },
    {
        id: 10,
        teacherId: "TCH010",
        name: "Jack Anderson",
        email: "jack.anderson@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "888-999-0000",
        subjects: ["Geography", "Computer Science"],
        classes: ["9A", "12B"],
        address: "707 Redwood Rd, Anytown",
    },
    {
        id: 11,
        teacherId: "TCH011",
        name: "Kelly Thomas",
        email: "kelly.thomas@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "999-000-1111",
        subjects: ["Music", "Art"],
        classes: ["11C", "10C"],
        address: "808 Olive Ln, Anytown",
    },
    {
        id: 12,
        teacherId: "TCH012",
        name: "Liam Jackson",
        email: "liam.jackson@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "000-111-2222",
        subjects: ["Drama", "Physical Education"],
        classes: ["12C", "9B"],
        address: "909 Cherry Ct, Anytown",
    },
    {
        id: 13,
        teacherId: "TCH013",
        name: "Mia White",
        email: "mia.white@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "111-222-3333",
        subjects: ["Mathematics", "English"],
        classes: ["10A", "12A"],
        address: "1010 Pine Pl, Anytown",
    },
    {
        id: 14,
        teacherId: "TCH014",
        name: "Noah Harris",
        email: "noah.harris@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "222-333-4444",
        subjects: ["Biology", "History"],
        classes: ["11A", "9C"],
        address: "1111 Oak Way, Anytown",
    },
    {
        id: 15,
        teacherId: "TCH015",
        name: "Olivia Martin",
        email: "olivia.martin@example.com",
        photo: "/avator.png", // Replace with actual image path
        phone: "333-444-5555",
        subjects: ["Chemistry", "Geography"],
        classes: ["12B", "10B"],
        address: "1212 Elm St, Anytown",
    },
];

export const studentsData = [
    {
        id: 1,
        studentId: "STD001",
        name: "Aaliyah Brown",
        email: "aaliyah.brown@example.com",
        photo: "/avator.png",
        phone: "123-456-1001",
        grade: "10",
        class: "10A",
        address: "101 Elm St, Anytown",
    },
    {
        id: 2,
        studentId: "STD002",
        name: "Ethan Davis",
        email: "ethan.davis@example.com",
        photo: "/avator.png",
        phone: "123-456-1002",
        grade: "11",
        class: "11B",
        address: "202 Oak Ave, Anytown",
    },
    {
        id: 3,
        studentId: "STD003",
        name: "Sophia Wilson",
        email: "sophia.wilson@example.com",
        photo: "/avator.png",
        phone: "123-456-1003",
        grade: "12",
        class: "12C",
        address: "303 Pine Ln, Anytown",
    },
    {
        id: 4,
        studentId: "STD004",
        name: "Liam Garcia",
        email: "liam.garcia@example.com",
        photo: "/avator.png",
        phone: "123-456-1004",
        grade: "9",
        class: "9A",
        address: "404 Maple Dr, Anytown",
    },
    {
        id: 5,
        studentId: "STD005",
        name: "Olivia Rodriguez",
        email: "olivia.rodriguez@example.com",
        photo: "/avator.png",
        phone: "123-456-1005",
        grade: "10",
        class: "10B",
        address: "505 Cedar Ct, Anytown",
    },
    {
        id: 6,
        studentId: "STD006",
        name: "Noah Martinez",
        email: "noah.martinez@example.com",
        photo: "/avator.png",
        phone: "123-456-1006",
        grade: "11",
        class: "11A",
        address: "606 Birch Pl, Anytown",
    },
    {
        id: 7,
        studentId: "STD007",
        name: "Ava Hernandez",
        email: "ava.hernandez@example.com",
        photo: "/avator.png",
        phone: "123-456-1007",
        grade: "12",
        class: "12B",
        address: "707 Willow Way, Anytown",
    },
    {
        id: 8,
        studentId: "STD008",
        name: "William Lopez",
        email: "william.lopez@example.com",
        photo: "/avator.png",
        phone: "123-456-1008",
        grade: "9",
        class: "9C",
        address: "808 Spruce St, Anytown",
    },
    {
        id: 9,
        studentId: "STD009",
        name: "Isabella Gonzalez",
        email: "isabella.gonzalez@example.com",
        photo: "/avator.png",
        phone: "123-456-1009",
        grade: "10",
        class: "10C",
        address: "909 Redwood Rd, Anytown",
    },
    {
        id: 10,
        studentId: "STD010",
        name: "James Perez",
        email: "james.perez@example.com",
        photo: "/avator.png",
        phone: "123-456-1010",
        grade: "11",
        class: "11C",
        address: "1010 Olive Ln, Anytown",
    },
    {
        id: 11,
        studentId: "STD011",
        name: "Mia Sanchez",
        email: "mia.sanchez@example.com",
        photo: "/avator.png",
        phone: "123-456-1011",
        grade: "12",
        class: "12A",
        address: "1111 Cherry Ct, Anytown",
    },
    {
        id: 12,
        studentId: "STD012",
        name: "Benjamin Ramirez",
        email: "benjamin.ramirez@example.com",
        photo: "/avator.png",
        phone: "123-456-1012",
        grade: "9",
        class: "9B",
        address: "1212 Pine Pl, Anytown",
    },
    {
        id: 13,
        studentId: "STD013",
        name: "Charlotte Torres",
        email: "charlotte.torres@example.com",
        photo: "/avator.png",
        phone: "123-456-1013",
        grade: "10",
        class: "10A",
        address: "1313 Oak Way, Anytown",
    },
    {
        id: 14,
        studentId: "STD014",
        name: "Elijah Flores",
        email: "elijah.flores@example.com",
        photo: "/avator.png",
        phone: "123-456-1014",
        grade: "11",
        class: "11B",
        address: "1414 Elm St, Anytown",
    },
    {
        id: 15,
        studentId: "STD015",
        name: "Amelia Rivera",
        email: "amelia.rivera@example.com",
        photo: "/avator.png",
        phone: "123-456-1015",
        grade: "12",
        class: "12C",
        address: "1515 Oak Ave, Anytown",
    },
    {
        id: 16,
        studentId: "STD016",
        name: "Lucas Reyes",
        email: "lucas.reyes@example.com",
        photo: "/avator.png",
        phone: "123-456-1016",
        grade: "9",
        class: "9A",
        address: "1616 Pine Ln, Anytown",
    },
    {
        id: 17,
        studentId: "STD017",
        name: "Harper Howard",
        email: "harper.howard@example.com",
        photo: "/avator.png",
        phone: "123-456-1017",
        grade: "10",
        class: "10B",
        address: "1717 Maple Dr, Anytown",
    },
    {
        id: 18,
        studentId: "STD018",
        name: "Henry Reed",
        email: "henry.reed@example.com",
        photo: "/avator.png",
        phone: "123-456-1018",
        grade: "11",
        class: "11A",
        address: "1818 Cedar Ct, Anytown",
    },
    {
        id: 19,
        studentId: "STD019",
        name: "Evelyn Bailey",
        email: "evelyn.bailey@example.com",
        photo: "/avator.png",
        phone: "123-456-1019",
        grade: "12",
        class: "12B",
        address: "1919 Birch Pl, Anytown",
    },
    {
        id: 20,
        studentId: "STD020",
        name: "Alexander Bell",
        email: "alexander.bell@example.com",
        photo: "/avator.png",
        phone: "123-456-1020",
        grade: "9",
        class: "9C",
        address: "2020 Willow Way, Anytown",
    },
    {
        id: 21,
        studentId: "STD021",
        name: "Scarlett Cook",
        email: "scarlett.cook@example.com",
        photo: "/avator.png",
        phone: "123-456-1021",
        grade: "10",
        class: "10C",
        address: "2121 Spruce St, Anytown",
    },
    {
        id: 22,
        studentId: "STD022",
        name: "Daniel Murphy",
        email: "daniel.murphy@example.com",
        photo: "/avator.png",
        phone: "123-456-1022",
        grade: "11",
        class: "11C",
        address: "2222 Redwood Rd, Anytown",
    },
    {
        id: 23,
        studentId: "STD023",
        name: "Grace Nelson",
        email: "grace.nelson@example.com",
        photo: "/avator.png",
        phone: "123-456-1023",
        grade: "12",
        class: "12A",
        address: "2323 Olive Ln, Anytown",
    },
    {
        id: 24,
        studentId: "STD024",
        name: "Matthew Carter",
        email: "matthew.carter@example.com",
        photo: "/avator.png",
        phone: "123-456-1024",
        grade: "9",
        class: "9B",
        address: "2424 Cherry Ct, Anytown",
    },
    {
        id: 25,
        studentId: "STD025",
        name: "Victoria Mitchell",
        email: "victoria.mitchell@example.com",
        photo: "/avator.png",
        phone: "123-456-1025",
        grade: "10",
        class: "10A",
        address: "2525 Pine Pl, Anytown",
    },
];

export const parentsData  = [
    {
        id: "PAR001",
        username: "john.doe",
        surname: "Doe",
        email: "john.doe@example.com",
        phone: "1234567890",
        address: "123 Main St, Anytown",
        img: "/images/parent1.jpg",
        bloodType: "A+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[0].name]
        
    },
    {
        id: "PAR002",
        username: "jane.smith",
        surname: "Smith",
        email: "jane.smith@example.com",
        phone: "9876543210",
        address: "456 Oak Ave, Anytown",
        img: "/images/parent2.jpg",
        bloodType: "O-",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[1].name, studentsData[2].name]
    },
    {
        id: "PAR003",
        username: "david.lee",
        surname: "Lee",
        email: "david.lee@example.com",
        phone: "5551234567",
        address: "789 Pine Ln, Anytown",
        img: "/images/parent3.jpg",
        bloodType: "B+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[3].name]
    },
    {
        id: "PAR004",
        username: "susan.jones",
        surname: "Jones",
        email: "susan.jones@example.com",
        phone: "1112223333",
        address: "101 Elm Rd, Anytown",
        img: "/images/parent4.jpg",
        bloodType: "AB-",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[4].name, studentsData[5].name]
    },
    {
        id: "PAR005",
        username: "michael.brown",
        surname: "Brown",
        email: "michael.brown@example.com",
        phone: "4445556666",
        address: "202 Maple Dr, Anytown",
        img: "/images/parent5.jpg",
        bloodType: "A-",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[6].name]
    },
    {
        id: "PAR006",
        username: "linda.davis",
        surname: "Davis",
        email: "linda.davis@example.com",
        phone: "7778889999",
        address: "303 Cedar Ct, Anytown",
        img: "/images/parent6.jpg",
        bloodType: "O+",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[7].name, studentsData[8].name]
    },
    {
        id: "PAR007",
        username: "robert.wilson",
        surname: "Wilson",
        email: "robert.wilson@example.com",
        phone: "2223334444",
        address: "404 Birch Pl, Anytown",
        img: "/images/parent7.jpg",
        bloodType: "B-",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[9].name]
    },
    {
        id: "PAR008",
        username: "mary.moore",
        surname: "Moore",
        email: "mary.moore@example.com",
        phone: "6667778888",
        address: "505 Willow Way, Anytown",
        img: "/images/parent8.jpg",
        bloodType: "AB+",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[10].name]
    },
    {
        id: "PAR009",
        username: "william.taylor",
        surname: "Taylor",
        email: "william.taylor@example.com",
        phone: "3334445555",
        address: "606 Spruce St, Anytown",
        img: "/images/parent9.jpg",
        bloodType: "A+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[11].name]
    },
    {
        id: "PAR010",
        username: "patricia.anderson",
        surname: "Anderson",
        email: "patricia.anderson@example.com",
        phone: "8889990000",
        address: "707 Redwood Rd, Anytown",
        img: "/images/parent10.jpg",
        bloodType: "O-",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[12].name]
    },
    {
        id: "PAR011",
        username: "richard.thomas",
        surname: "Thomas",
        email: "richard.thomas@example.com",
        phone: "9990001111",
        address: "808 Olive Ln, Anytown",
        img: "/images/parent11.jpg",
        bloodType: "B+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[13].name]
    },
    {
        id: "PAR012",
        username: "jennifer.jackson",
        surname: "Jackson",
        email: "jennifer.jackson@example.com",
        phone: "0001112222",
        address: "909 Cherry Ct, Anytown",
        img: "/images/parent12.jpg",
        bloodType: "AB-",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[14].name]
    },
    {
        id: "PAR013",
        username: "joseph.white",
        surname: "White",
        email: "joseph.white@example.com",
        phone: "1112223333",
        address: "1010 Pine Pl, Anytown",
        img: "/images/parent13.jpg",
        bloodType: "A-",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[15].name]
    },
    {
        id: "PAR014",
        username: "dorothy.harris",
        surname: "Harris",
        email: "dorothy.harris@example.com",
        phone: "2223334444",
        address: "1111 Oak Way, Anytown",
        img: "/images/parent14.jpg",
        bloodType: "O+",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[16].name, studentsData[17].name]
    },
    {
        id: "PAR015",
        username: "charles.martin",
        surname: "Martin",
        email: "charles.martin@example.com",
        phone: "3334445555",
        address: "1212 Elm St, Anytown",
        img: "/images/parent15.jpg",
        bloodType: "B-",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[18].name]
    },
    {
        id: "PAR016",
        username: "margaret.thompson",
        surname: "Thompson",
        email: "margaret.thompson@example.com",
        phone: "4445556666",
        address: "1313 Oak Ave, Anytown",
        img: "/images/parent16.jpg",
        bloodType: "AB+",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[19].name, studentsData[20].name]
    },
    {
        id: "PAR017",
        username: "steven.garcia",
        surname: "Garcia",
        email: "steven.garcia@example.com",
        phone: "5556667777",
        address: "1414 Pine Ln, Anytown",
        img: "/images/parent17.jpg",
        bloodType: "A+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[21].name, studentsData[22].name]
    },
    {
        id: "PAR018",
        username: "sandra.rodriguez",
        surname: "Rodriguez",
        email: "sandra.rodriguez@example.com",
        phone: "6667778888",
        address: "1515 Maple Dr, Anytown",
        img: "/images/parent18.jpg",
        bloodType: "O-",
        sex: "FEMALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[23].name]
    },
    {
        id: "PAR019",
        username: "paul.martinez",
        surname: "Martinez",
        email: "paul.martinez@example.com",
        phone: "7778889999",
        address: "1616 Cedar Ct, Anytown",
        img: "/images/parent19.jpg",
        bloodType: "B+",
        sex: "MALE",
        createdAt: new Date(),
        updatedAt: new Date(),
        students: [studentsData[24].name]
    },
];

export const subjectsData = [
    {
        id: 1,
        name: "Mathematics",
        teachers: [teachersData[0].name], // Alice Johnson teaches Mathematics
        lessons: [],
    },
    {
        id: 2,
        name: "English",
        teachers: [teachersData[1].name], // Bob Smith teaches English
        lessons: [],
    },
    {
        id: 3,
        name: "Biology",
        teachers: [teachersData[2].name], // Carol Williams teaches Biology
        lessons: [],
    },
    {
        id: 4,
        name: "Computer Science",
        teachers: [teachersData[4].name, teachersData[3].name], // Eve Davis and David Brown teach Computer Science
        lessons: [],
    },
    {
        id: 5,
        name: "History",
        teachers: [teachersData[1].name], // Bob Smith teaches History
        lessons: [],
    },
    {
        id: 6,
        name: "Chemistry",
        teachers: [teachersData[2].name], // Carol Williams teaches Chemistry
        lessons: [],
    },
    {
        id: 7,
        name: "Geography",
        teachers: [teachersData[3].name], // David Brown teachers Geography
        lessons: [],
    },
    {
        id: 8,
        name: "Art",
        teachers: [teachersData[5].name], // Eve Davis teaches Art
        lessons: [],
    },
];

export const classData = [
    {
        id: 1,
        name: "Class A",
        capacity: 30,
        supervisorId: teachersData[3].name,
        
    },
    {
        id: 2,
        name: "Class B",
        capacity: 25,
        supervisorId: teachersData[0].name,
        
    },
    {
        id: 3,
        name: "Class C",
        capacity: 35,
        supervisorId: teachersData[2].name,
        

    },
    {
        id: 4,
        name: "Class D",
        capacity: 20,
        supervisorId: teachersData[5].name,
        
    },
    {
        id: 5,
        name: "Class E",
        capacity: 30,
        supervisorId: teachersData[13].name,
        
    },
];

export const lessonData = [
    {
        id: 1,
        name: "Math 101",
        day: "Monday",
        startTime: new Date("2023-10-27T09:00:00Z"),
        endTime: new Date("2023-10-27T10:00:00Z"),
        subject: subjectsData[0].name,
        class: classData[0].name,
        teacher: teachersData[0].name,
        
    },
    {
        id: 2,
        name: "English Lit",
        day: "Wednesday",
        startTime: new Date("2023-10-27T11:00:00Z"),
        endTime: new Date("2023-10-27T12:00:00Z"),
        subject: subjectsData[1].name,
        class: classData[1].name,
        teacher: teachersData[1].name,
    },
    {
        id: 3,
        name: "Science Lab",
        day: "Friday",
        startTime: new Date("2023-10-27T13:00:00Z"),
        endTime: new Date("2023-10-27T14:30:00Z"),
        subject: subjectsData[2].name,
        class: classData[2].name,
        teacher: teachersData[2].name,
    },
    {
        id: 4,
        name: "History",
        day: "Tuesday",
        startTime: new Date("2023-10-27T10:00:00Z"),
        endTime: new Date("2023-10-27T11:00:00Z"),
        subject: subjectsData[4].name,
        class: classData[4].name,
        teacher: teachersData[4].name,
    },
    {
        id: 5,
        name: "Art",
        day: "Thursday",
        startTime: new Date("2023-10-27T14:00:00Z"),
        endTime: new Date("2023-10-27T15:00:00Z"),
        subject: subjectsData[3].name,
        class: classData[3].name,
        teacher: teachersData[3].name,
    },

];

export const examData = [
    {
        id: 1,
        subject: "Math",
        class: "Class A",
        teacher: teachersData[0].name,
        date: "2025-04-15",
    },
    {
        id: 2,
        subject: "English",
        class: "Class B",
        teacher: teachersData[1].name,
        date: "2025-04-16",
    },
    {
        id: 3,
        subject: "Science",
        class: "Class C",
        teacher: teachersData[2].name,
        date: "2025-04-17",
    },
    {
        id: 4,
        subject: "History",
        class: "Class D",
        teacher: teachersData[3].name,
        date: "2025-04-18",
    },
    {
        id: 5,
        subject: "Art",
        class: "Class E",
        teacher: teachersData[4].name,
        date: "2025-04-19",
    },

];

export const assignmentData= [
    {
        id: 1,
        subject: "Math",
        class: "Class A",
        teacher: "Teacher 1",
        dueDate: "2025-04-20",
    },
    {
        id: 2,
        subject: "English",
        class: "Class B",
        teacher: "Teacher 2",
        dueDate: "2025-04-22",
    },
    {
        id: 3,
        subject: "Science",
        class: "Class C",
        teacher: "Teacher 3",
        dueDate: "2025-04-24",
    },
    {
        id: 4,
        subject: "History",
        class: "Class D",
        teacher: "Teacher 4",
        dueDate: "2025-04-26",
    },
    {
        id: 5,
        subject: "Art",
        class: "Class E",
        teacher: "Teacher 5",
        dueDate: "2025-04-28",
    },
];

export const resultData = [
    {
        id: "result-1",
        subject: "Math",
        class: "Class A",
        teacher: "Teacher 1",
        student: "Student 1",
        type: "exam",
        data: "2025-11-15",
        score: 85,
    },
    {
        id: "result-2",
        subject: "English",
        class: "Class B",
        teacher: "Teacher 2",
        student: "Student 2",
        type: "assignment",
        data: "2025-11-22",
        score: 92,
    },
    {
        id: "result-3",
        subject: "Science",
        class: "Class C",
        teacher: "Teacher 3",
        student: "Student 3",
        type: "exam",
        data: "2025-11-17",
        score: 78,
    },
    {
        id: "result-4",
        subject: "History",
        class: "Class D",
        teacher: "Teacher 4",
        student: "Student 4",
        type: "assignment",
        data: "2025-11-26",
        score: 95,
    },
    {
        id: "result-5",
        subject: "Art",
        class: "Class E",
        teacher: "Teacher 5",
        student: "Student 5",
        type: "exam",
        data: "2025-11-19",
        score: 88,
    },
    {
        id: "result-6",
        subject: "Math",
        class: "Class A",
        teacher: "Teacher 1",
        student: "Student 2",
        type: "assignment",
        data: "2025-11-20",
        score: 70,
    },
    {
        id: "result-7",
        subject: "English",
        class: "Class B",
        teacher: "Teacher 2",
        student: "Student 3",
        type: "exam",
        data: "2025-11-16",
        score: 90,
    },
    {
        id: "result-8",
        subject: "Science",
        class: "Class C",
        teacher: "Teacher 3",
        student: "Student 4",
        type: "assignment",
        data: "2025-11-24",
        score: 82,
    },
    {
        id: "result-9",
        subject: "History",
        class: "Class D",
        teacher: "Teacher 4",
        student: "Student 5",
        type: "exam",
        data: "2025-11-18",
        score: 75,
    },
    {
        id: "result-10",
        subject: "Art",
        class: "Class E",
        teacher: "Teacher 5",
        student: "Student 1",
        type: "assignment",
        data: "2025-11-28",
        score: 98,
    },
];



export const eventData = [
    {
        id: 1,
        title: "Class A Field Trip",
        class: "Class A",
        date: "2025-12-05",
        startTime: "09:00",
        endTime: "15:00",
    },
    {
        id: 2,
        title: "Class B Science Fair",
        class: "Class B",
        date: "2025-12-10",
        startTime: "10:00",
        endTime: "16:00",
    },
    {
        id: 3,
        title: "Class C Parent-Teacher Meeting",
        class: "Class C",
        date: "2025-12-15",
        startTime: "14:00",
        endTime: "18:00",
    },
    {
        id: 4,
        title: "Class D Art Exhibition",
        class: "Class D",
        date: "2025-12-20",
        startTime: "11:00",
        endTime: "17:00",
    },
    {
        id: 5,
        title: "Class E Holiday Party",
        class: "Class E",
        date: "2025-12-22",
        startTime: "12:00",
        endTime: "16:00",
    },
    {
        id: 6,
        title: "Class A Math Competition",
        class: "Class A",
        date: "2025-12-07",
        startTime: "10:00",
        endTime: "13:00",
    },
    {
        id: 7,
        title: "Class B Book Club Meeting",
        class: "Class B",
        date: "2025-12-12",
        startTime: "15:00",
        endTime: "17:00",
    },
    {
        id: 8,
        title: "Class C Sports Day",
        class: "Class C",
        date: "2025-12-17",
        startTime: "09:30",
        endTime: "14:30",
    },
    {
        id: 9,
        title: "Class D Music Performance",
        class: "Class D",
        date: "2025-12-21",
        startTime: "18:00",
        endTime: "20:00",
    },
    {
        id: 10,
        title: "Class E Career Day",
        class: "Class E",
        date: "2025-12-23",
        startTime: "10:30",
        endTime: "15:30",
    },
    {
        id: 11,
        title: "Class A History Project Presentation",
        class: "Class A",
        date: "2025-12-09",
        startTime: "13:00",
        endTime: "15:00",
    },
    {
        id: 12,
        title: "Class B Coding Workshop",
        class: "Class B",
        date: "2025-12-14",
        startTime: "11:00",
        endTime: "14:00",
    },
];

export const announcementData = [
    {
        id: 1,
        title: "Math Exam Postponed",
        class: "Class A",
        date: "2025-11-10",
    },
    {
        id: 2,
        title: "English Assignment Due Next Week",
        class: "Class B",
        date: "2025-11-12",
    },
    {
        id: 3,
        title: "Science Lab Cancelled",
        class: "Class C",
        date: "2025-11-15",
    },
    {
        id: 4,
        title: "History Field Trip Information",
        class: "Class D",
        date: "2025-11-18",
    },
    {
        id: 5,
        title: "Art Supply List",
        class: "Class E",
        date: "2025-11-20",
    },
    {
        id: 6,
        title: "Math Review Session",
        class: "Class A",
        date: "2025-11-22",
    },
    {
        id: 7,
        title: "English Book Discussion",
        class: "Class B",
        date: "2025-11-24",
    },
    {
        id: 8,
        title: "Science Project Guidelines",
        class: "Class C",
        date: "2025-11-26",
    },
    {
        id: 9,
        title: "History Quiz Announcement",
        class: "Class D",
        date: "2025-11-28",
    },
    {
        id: 10,
        title: "Art Exhibition Reminder",
        class: "Class E",
        date: "2025-11-30",
    },
    {
        id: 11,
        title: "Class A Holiday Party Info",
        class: "Class A",
        date: "2025-12-01",
    },
    {
        id: 12,
        title: "Class B Book Club Change",
        class: "Class B",
        date: "2025-12-03",
    },
    {
        id: 13,
        title: "Class C Sports Day Signups",
        class: "Class C",
        date: "2025-12-05",
    },
    {
        id: 14,
        title: "Class D Music Performance Tickets",
        class: "Class D",
        date: "2025-12-07",
    },
    {
        id: 15,
        title: "Class E Career Day Schedule",
        class: "Class E",
        date: "2025-12-09",
    },
];

